workflows:
  ios-app:
    name: iOS App
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild clean archive \
            -scheme "MovieApp" \
            -sdk iphoneos \
            -archivePath build/MovieApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Create IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/MovieApp.xcarchive \
            -exportPath build/MovieApp.ipa \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/MovieApp.ipa
