workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.MovieApp"
        CM_CERTIFICATE: ${CM_CERTIFICATE}
        CM_CERTIFICATE_PASSWORD: ${CM_CERTIFICATE_PASSWORD}
        CM_PROVISIONING_PROFILE: ${CM_PROVISIONING_PROFILE}
    scripts:
      - name: Set up keychain
        script: |
          echo "Setting up keychain..."
          keychain initialize
          
          # Add certificate
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
          
          # Add provisioning profile
          echo $CM_PROVISIONING_PROFILE | base64 --decode > /tmp/00008130-001C6C100151001C.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/00008130-001C6C100151001C.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
      - name: Install XcodeGen
        script: |
          brew install xcodegen
          
      - name: Generate Xcode Project
        script: |
          cd $CM_BUILD_DIR
          xcodegen generate
          
      - name: Build and Export IPA
        script: |
          cd $CM_BUILD_DIR
          
          # Build archive
          xcodebuild clean archive \
            -project MovieApp.xcodeproj \
            -scheme MovieApp \
            -configuration Debug \
            -archivePath build/MovieApp.xcarchive \
            CODE_SIGN_IDENTITY="Apple Development" \
            DEVELOPMENT_TEAM="38X4H45H4M" \
            PROVISIONING_PROFILE_SPECIFIER="00008130-001C6C100151001C" \
            CODE_SIGN_STYLE="Manual"
          
          # Export archive to IPA
          xcodebuild -exportArchive \
            -archivePath build/MovieApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ \
            -allowProvisioningUpdates \
            -verbose
            
    artifacts:
      - build/MovieApp.ipa
      - build/**/*.app
      - build/**/*.ipa
      - build/MovieApp.xcarchive/dSYMs/*.dSYM
