workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Debug Info
        script: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nMovieApp directory:"
          ls -la MovieApp
          echo "\nProject structure:"
          find . -type f
          echo "\nXcode version:"
          xcodebuild -version
          
      - name: Set up build directory
        script: |
          # Navigate to project directory
          cd $CM_BUILD_DIR
          
          # Create build directory
          mkdir -p build
          
      - name: Build for simulator
        script: |
          # Navigate to project directory
          cd $CM_BUILD_DIR
          
          # Build for simulator
          xcodebuild clean build \
            -project MovieApp.xcodeproj \
            -scheme MovieApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_VERSION=5.0 \
            DEVELOPMENT_TEAM="" \
            PRODUCT_BUNDLE_IDENTIFIER="com.example.MovieApp" \
            ASSETCATALOG_COMPILER_APPICON_NAME="" \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=YES \
            -derivedDataPath build \
            -verbose || exit 1
            
      - name: Archive and export IPA
        script: |
          # Navigate to project directory
          cd $CM_BUILD_DIR
          
          # Archive for device
          xcodebuild clean archive \
            -project MovieApp.xcodeproj \
            -scheme MovieApp \
            -configuration Debug \
            -sdk iphoneos \
            -archivePath build/MovieApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_VERSION=5.0 \
            DEVELOPMENT_TEAM="" \
            PRODUCT_BUNDLE_IDENTIFIER="com.example.MovieApp" \
            ASSETCATALOG_COMPILER_APPICON_NAME="" \
            ENABLE_BITCODE=NO \
            -verbose || exit 1
            
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/MovieApp.xcarchive \
            -exportPath build/MovieApp \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO || exit 1
            
    artifacts:
      - build/**/*.app
      - build/**/*.ipa
      - build/MovieApp.xcarchive/dSYMs/*.dSYM
