workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.MovieApp"
    scripts:
      - name: Generate Xcode Project
        script: |
          cd $CM_BUILD_DIR
          xcodegen generate
          
      - name: Build and Export IPA
        script: |
          cd $CM_BUILD_DIR
          
          # Build archive
          xcodebuild clean archive \
            -project MovieApp.xcodeproj \
            -scheme MovieApp \
            -configuration Debug \
            -archivePath build/MovieApp.xcarchive \
            CODE_SIGN_IDENTITY="Apple Development" \
            DEVELOPMENT_TEAM="38X4H45H4M" \
            CODE_SIGN_STYLE="Automatic"
          
          # Export archive to IPA
          xcodebuild -exportArchive \
            -archivePath build/MovieApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ \
            -allowProvisioningUpdates \
            -verbose
            
    artifacts:
      - build/MovieApp.ipa
      - build/**/*.app
      - build/**/*.ipa
      - build/MovieApp.xcarchive/dSYMs/*.dSYM
