workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development
    scripts:
      - name: Build ipa for development
        script: |
          xcodebuild clean archive \
            -project MovieApp.xcodeproj \
            -scheme MovieApp \
            -sdk iphoneos \
            -configuration Debug \
            -archivePath build/MovieApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
            -archivePath build/MovieApp.xcarchive \
            -exportPath build/MovieApp \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/**/*.ipa
      - build/MovieApp.xcarchive/dSYMs/*.dSYM
